#!/bin/bash

# Exit the script when a command returns a non true value.
set -e
# Prevent using unset variables.
set -u

DISTRIBUTOR=$(lsb_release -is)
CODENAME=$(lsb_release -cs)
PWD=$(pwd)

if [[ -d "$DISTRIBUTOR/$CODENAME" ]]; then
  echo "Found supported OS in $PWD/$DISTRIBUTOR/$CODENAME"
else
  echo "Your OS is not supported yet"
  echo "Check the pull requests or create your own!"
fi
