#!/bin/bash

. include/bootstrap

echo -e $SERVERPLOP"Installing CodeSniffer"

sudo apt-get update -y >/dev/null 2>&1
sudo apt-get install -y php-pear >/dev/null 2>&1

sudo pear config-set auto_discover 1 >/dev/null 2>&1
sudo pear upgrade PEAR >/dev/null 2>&1
sudo pear upgrade PHP_CodeSniffer >/dev/null 2>&1
sudo pear config-set auto_discover 0 >/dev/null 2>&1

# Conjur up an alias to enforce PSR2.
ALIASLINE="alias phpcs='phpcs --standard=PSR2'"

if grep -q 'alias phpcs' ~/.bashrc >/dev/null 2>&1; then
  echo -e $SERVERPLOP"Prevented double alias for phpcs"
else
  echo -e $SERVERPLOP"Adding phpcs alias"
  echo $ALIASLINE >> ~/.bashrc
fi

echo -e $SERVERPLOP"Finished CodeSniffer"
