#!/bin/bash

. include/bootstrap
. include/apt

dependencies=(
  'flex'
  'bison'
);

OPWD=$(pwd)
cd /tmp

log "Installing Doxygen"

# Remove trash.
sudo rm -rf doxygen-1.8.4* >/dev/null 2>&1

if which doxygen >/dev/null 2>&1; then
  log "Doxygen already installed."
  log "Updating dependencies."
  aptinstall ${dependencies[@]}
else
  # Install dependencies.
  log "Installing dependencies."
  aptinstall ${dependencies[@]}

  # Download the Doxygen package.
  run wget http://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.4.src.tar.gz

  # Extract the package.
  run gunzip doxygen-1.8.4.src.tar.gz
  run tar xf doxygen-1.8.4.src.tar
  cd doxygen-1.8.4

  # Configure the package.
  run sh ./configure

  # Run the installation.
  run make
  run sudo make install

  cd /tmp

  # Remove trash.
  sudo rm -rf doxygen-1.8.4* >/dev/null 2>&1

  # Run the Doxywizard.
  touch ~/Doxyfile >/dev/null 2>&1

  log "Your Doxyfile was stored in ~/Doxyfile"
fi

cd $OPWD

loginfo "Installed version: doxygen $GREEN$(doxygen --version)$NOCLR"
log "Finished Doxygen"
