#!/bin/bash

. include/bootstrap

OPWD=$(pwd)
cd /tmp

log "Installing Doxygen"

# Remove trash.
sudo rm -rf doxygen-1.8.4* >/dev/null 2>&1

if which doxygen >/dev/null 2>&1; then
  log "Doxygen already installed. No update mechanism in place."
else
  # Install dependencies.
  sudo apt-get update -y >/dev/null 2>&1
  sudo apt-get install -y flex bison >/dev/null 2>&1

  # Download the Doxygen package.
  wget http://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.4.src.tar.gz >/dev/null 2>&1

  # Extract the package.
  gunzip doxygen-1.8.4.src.tar.gz >/dev/null 2>&1
  tar xf doxygen-1.8.4.src.tar >/dev/null 2>&1
  cd doxygen-1.8.4

  # Configure the package.
  sh ./configure >/dev/null 2>&1

  # Run the installation.
  make >/dev/null 2>&1
  sudo make install >/dev/null 2>&1

  cd /tmp

  # Remove trash.
  sudo rm -rf doxygen-1.8.4* >/dev/null 2>&1

  # Run the Doxywizard.
  touch ~/Doxyfile >/dev/null 2>&1

  log "Your Doxyfile was stored in ~/Doxyfile"
fi

cd $OPWD

log "Finished Doxygen"
