#!/bin/bash

. include/bootstrap-root

packages=(
  'adjtimex'
  'build-essential'
  'bzip2'
  'curl'
  'debhelper'
  'denyhosts'
  'gcc'
  'git'
  'git-core'
  'htop'
  'less'
  'libssl-dev'
  'make'
  'openssh-server'
  'openssl'
  'pari-gp'
  'screen'
  'sysstat'
  'vim'
  'zip'
);

log "Installing Linux essentials"
log "Selected packages: ${packages[@]}"

apt-get update -y >/dev/null 2>&1
apt-get install -y ${packages[@]} >/dev/null 2>&1

log "Finished Linux essentials"
