#!/bin/bash

. include/bootstrap-root
. include/apt

packages=(
  'adjtimex'
  'build-essential'
  'bzip2'
  'curl'
  'debhelper'
  'denyhosts'
  'gcc'
  'git'
  'git-core'
  'htop'
  'less'
  'libssl-dev'
  'make'
  'openssh-server'
  'openssl'
  'pari-gp'
  'screen'
  'sysstat'
  'vim'
  'zip'
);

log "Installing Linux essentials"

aptinstall ${packages[@]}

log "Finished Linux essentials"
