#!/bin/bash

. include/bootstrap-root
. include/apt

SOURCE="/etc/apt/sources.list.d/webupd8team-java.list"
FRESH=0

log "Installing Java 8"

# We have a version of Java installed. Not sure if it's OpenJDK or Oracle.
if which java >/dev/null 2>&1; then
  # We found the source listing for the webupd8team. Assuming Oracle's version is
  # installed.
  if ls $SOURCE >/dev/null 2>&1; then
    log "Skipping OpenJDK purge and source listing."
    FRESH=1
  fi
fi

# We found a fresh installation / an OpenJDK installation.
if [[ $FRESH -eq 0 ]]; then
  apt-get purge openjdk* >/dev/null 2>&1

  echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu precise main" > $SOURCE
  echo "deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu precise main" >> $SOURCE

  apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EEA14886 >/dev/null 2>&1
fi

# Update and install our Java.
if which java >/dev/null 2>&1; then
  aptinstall oracle-java8-installer
else
  log "Running verbose installation."
  loginfo "Installing Java 8 for the first time. You will be asked to accept their license."
  apt-get update -y
  apt-get install -y oracle-java8-installer
fi

log "Finished Java 8"
