#!/bin/bash

# Exit the script when a command returns a non true value.
set -e
# Prevent using unset variables.
set -u

if [[ $EUID -ne 0 ]]; then
  echo "$0 must be run as root"
  exit 1
fi

SOURCE="/etc/apt/sources.list.d/webupd8team-java.list"
FRESH=0

# We have a version of Java installed. Not sure if it's OpenJDK or Sun.
if which java; then
  # We found the source listing for the webupd8team. Assuming Sun's version is
  # installed.
  if ls $SOURCE; then
    echo "Skipping OpenJDK purge and source listing."
    FRESH=1
  fi
fi

# We found a fresh installation / an OpenJDK installation.
if [[ $FRESH -eq 0 ]]; then
  apt-get purge openjdk*

  echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu precise main" > $SOURCE
  echo "deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu precise main" >> $SOURCE

  apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EEA14886
fi

# Update and install our Java.
apt-get update -y
apt-get install oracle-java8-installer -y
