#!/bin/bash

# Exit the script when a command returns a non true value.
set -e
# Prevent using unset variables.
set -u

if [[ $EUID -ne 0 ]]; then
  echo "$0 must be run as root"
  exit 1
fi

packages=(
  'mysql-server'
  'mysql-client'
);

# Install the php5-mysql package if php is available.
if which php; then
  packages=("${packages[@]}" 'php5-mysql')
fi

# Install this if Perl is available.
if which perl; then
  packages=("${packages[@]}" 'libdbd-mysql-perl' 'libtime-piece-mysql-perl')
fi

apt-get update -y >/dev/null 2>&1
apt-get install -y ${packages[@]}
