#!/bin/bash

# Exit the script when a command returns a non true value.
set -e
# Prevent using unset variables.
set -u

if [[ $EUID -ne 0 ]]; then
  echo "$0 must be run as root"
  exit 1
fi

OPAD=$(pwd)

cd /tmp

rm -rf node.latest
wget http://nodejs.org/dist/latest/SHASUMS.txt -O /tmp/node.latest

if [[ "$(uname -i)" == "x86_64" ]]; then
  LATESTNODE=$(grep linux-x64 /tmp/node.latest | cut -sd ' ' -f 3)
else
  LATESTNODE=$(grep linux-x86 /tmp/node.latest | cut -sd ' ' -f 3)
fi

VERSION=$(echo $LATESTNODE | cut -sd '.' -f 1,2,3 | cut -sd'-' -f 2)
REPO="https://github.com/joyent/node.git"
UPTODATE=1

# Check for an existing version of node.
if which node; then
  CURRENT=$(node -v)
  if [[ "$VERSION" == "$CURRENT" ]]; then
    UPTODATE=0
    echo "Node already up to date! Current version: $CURRENT"
  fi
fi

# Run update / install logic.
if [[ $UPTODATE -eq 0 ]]; then
  echo "Skipping update process"
else
  NEEDCLONE=0

  # Use an existing clone if it's available.
  if ls node; then
    echo "Using existing repository"
    cd node

    # Check if we can pull.
    if git pull; then
      echo "Updated source files via git pull"
      NEEDCLONE=1
    fi

    cd ..
  fi

  if [[ $NEEDCLONE -eq 0 ]]; then
    rm -rf node
    git clone $REPO
  fi

  cd node

  # Checkout to our specific version.
  git checkout $VERSION

  # Configure seems not to find libssl by default so we give it an explicit pointer.
  # Optionally: you can isolate node by adding --prefix=/opt/node
  ./configure --openssl-libpath=/usr/lib/ssl

  make
  make install
fi

cd $OPAD

node -v

