#!/bin/bash

# Exit the script when a command returns a non true value.
set -e
# Prevent using unset variables.
set -u

if [[ $EUID -ne 0 ]]; then
  echo "$0 must be run as root"
  exit 1
fi

apt-get update -y
apt-get install -y \
  libapache2-mod-perl2 \
  libbusiness-creditcard-perl \
  libcgi-session-perl \
  libclass-dbi-sqlite-perl \
  libconfig-ini-perl \
  libconvert-pem-perl \
  libcrypt-openssl-rsa-perl \
  libcrypt-openssl-x509-perl \
  libcrypt-ssleay-perl \
  libdatetime-perl \
  libdbd-mysql-perl \
  libdigest-sha1-perl \
  liberror-perl \
  libfreezethaw-perl \
  libhtml-scrubber-perl \
  libhtml-strip-perl \
  libhtml-stripscripts-parser-perl \
  libhtml-stripscripts-perl \
  libhttp-browserdetect-perl \
  libjson-perl \
  libmail-rfc822-address-perl \
  libmime-lite-perl \
  libnet-sftp-foreign-perl \
  libnet-ssleay-perl \
  libphp-serialization-perl \
  libreadonly-perl \
  libsoap-lite-perl \
  libsphinx-search-perl \
  libstring-approx-perl \
  libtemplate-perl \
  libtemplate-perl-doc \
  libtemplate-plugin-xml-perl \
  libtext-unaccent-perl \
  libtime-modules-perl \
  libtime-piece-mysql-perl \
  libtime-piece-perl \
  libxml-simple-perl \
  libxml-xpath-perl \
  libyaml-libyaml-perl \
  libyaml-perl \
  libyaml-syck-perl \

OPWD=$(pwd)

# Install cpanminus.
cd /opt
curl https://raw.github.com/miyagawa/cpanminus/master/cpanm > cpanm
chmod +x cpanm
ln -s /opt/cpanm /usr/bin/

# Upgrade cpanminus.
cpanm --self-upgrade
cpanm CPAN
cpanm YAML
cpanm Geo::Distance
cpanm URI::Escape::XS
cpanm Math::Pari

cd $OPWD
