#!/bin/bash

. include/bootstrap-root
. include/apt
. include/cpanm

packages=(
  'libbusiness-creditcard-perl'
  'libcgi-session-perl'
  'libclass-dbi-sqlite-perl'
  'libconfig-ini-perl'
  'libconvert-pem-perl'
  'libcrypt-openssl-rsa-perl'
  'libcrypt-openssl-x509-perl'
  'libcrypt-ssleay-perl'
  'libdatetime-perl'
  'libdbd-sqlite'
  'libdigest-sha1-perl'
  'liberror-perl'
  'libfreezethaw-perl'
  'libhtml-scrubber-perl'
  'libhtml-strip-perl'
  'libhtml-stripscripts-parser-perl'
  'libhtml-stripscripts-perl'
  'libhttp-browserdetect-perl'
  'libjson-perl'
  'libmail-rfc822-address-perl'
  'libmime-lite-perl'
  'libmodule-install-perl'
  'libnet-sftp-foreign-perl'
  'libnet-ssleay-perl'
  'libreadonly-perl'
  'libsoap-lite-perl'
  'libsphinx-search-perl'
  'libstring-approx-perl'
  'libtemplate-perl'
  'libtemplate-perl-doc'
  'libtemplate-plugin-xml-perl'
  'libtext-unaccent-perl'
  'libtime-modules-perl'
  'libtime-piece-perl'
  'libxml-simple-perl'
  'libxml-xpath-perl'
  'libyaml-libyaml-perl'
  'libyaml-perl'
  'libyaml-syck-perl'
);

# Install this module if Apache2 is available.
if [ -f /etc/init.d/apache2 ]; then
  packages=("${packages[@]}" 'libapache2-mod-perl2')
fi

# Install these modules if MySQL is available.
if [ -f /etc/init.d/mysql ]; then
  packages=("${packages[@]}" 'libdbd-mysql-perl' 'libtime-piece-mysql-perl')
fi

# Install this if PHP is available.
if which php >/dev/null 2>&1; then
  packages=("${packages[@]}" 'libphp-serialization-perl')
fi

log "Installing perl"

aptinstall ${packages[@]}

OPWD=$(pwd)

# Install cpanminus.
if which cpanm >/dev/null 2>&1; then
  log "cpanminus already installed. skipping to upgrade."
else
  cd /opt
  run rm -f cpanm
  log "Downloading cpanminus"
  curl -sL http://cpanmin.us > cpanm 2>&1
  run chmod +x cpanm
  run rm -f /usr/local/bin/cpanm
  run rm -f /usr/bin/cpanm
  run ln -s /opt/cpanm /usr/local/bin/
  run ln -s /opt/cpanm /usr/bin/
fi

# CPAN distributions.
distributions=(
  'YAML'
  'Geo::Distance'
  'URI::Escape::XS'
);

# Upgrade cpanminus.
cpanm --self-upgrade --sudo >/dev/null 2>&1
cpanminstall ${distributions[@]}

cd $OPWD

log "Finished perl"
