#!/bin/bash

. include/bootstrap-root
. include/apt

packages=(
  'php-htmlpurifier'
  'php5'
  'php5-cli'
  'php5-common'
  'php5-curl'
  'php5-gd'
  'php5-imagick'
  'php5-mcrypt'
  'php5-suhosin'
);

# Install this module if Apache2 is available.
if [ -f /etc/init.d/apache2 ]; then
  packages=("${packages[@]}" 'libapache2-mod-php5')
fi

# Install the mysql package if the server is available.
if [ -f /etc/init.d/mysql ]; then
  packages=("${packages[@]}" 'php5-mysql')
fi

# Install this if Perl is available.
if which perl >/dev/null 2>&1; then
  packages=("${packages[@]}" 'libphp-serialization-perl')
fi

log "Installing PHP"

aptinstall ${packages[@]}

log "Finished PHP"
