#!/bin/bash

# Exit the script when a command returns a non true value.
set -e
# Prevent using unset variables.
set -u

if [[ $EUID -ne 0 ]]; then
  echo "$0 must be run as root"
  exit 1
fi

packages=(
  'php-htmlpurifier'
  'php5'
  'php5-cli'
  'php5-common'
  'php5-curl'
  'php5-gd'
  'php5-imagick'
  'php5-mcrypt'
  'php5-suhosin'
);

# Install this module if Apache2 is available.
if ls /etc/init.d/apache2; then
  packages=("${packages[@]}" 'libapache2-mod-php5')
fi

# Install the mysql package if the server is available.
if ls /etc/init.d/mysql; then
  packages=("${packages[@]}" 'php5-mysql')
fi

# Install this if Perl is available.
if which perl; then
  packages=("${packages[@]}" 'libphp-serialization-perl')
fi

apt-get update -y
apt-get install -y ${packages[@]}
