#!/usr/bin/php
<?php
/**
 * Create a VirtualHost for webgrind on Apache2.
 *
 * @package Serverplop
 * @subpackage webgrind
 */

/**
 * Run a command as the current user.
 *
 * @param string $command
 * @return string $output
 */
function ido($command)
{
    exec(escapeshellcmd($command), $output);
    $output = trim(implode(PHP_EOL, $output));
    return $output;
}

if (ido('whoami') === 'root') {
    die('Cannot be run as root');
}

/**
 * Run a command as root. We do this in a seperate shell to lift our rights.
 *
 * @param string $command
 * @return string $output
 */
function sudo($command)
{
    $output = ido("sudo sh -c \"{$command}\"");
    return $output;
}

$vhostFile = '/etc/apache2/sites-available/webgrind.conf';

$hostName = ido('hostname');
$webgrindHostName = 'webgrind.' . $hostName;
$port = 80;

if (!file_exists($vhostFile)) {
    $documentRoot = '/www/webgrind';
    $log = '${APACHE_LOG_DIR}';
    $hostsFile = '/etc/hosts';

    // Get the local IP.
    $ip = ido('ifconfig | grep \'inet addr\' | grep Bcast | head -1');
    list(,$ip) = explode(' ', $ip);
    list(,$ip) = explode(':', $ip);

    $hostsRule = "{$ip}\t{$webgrindHostName}";

    // Check if we have to add a hosts rule.
    if ($hostsRule !== ido("grep '{$hostsRule}' {$hostsFile}")) {
        sudo("echo '{$hostsRule}' >> {$hostsFile}");
    }

    // Create a VirtualHost.
    $vhost = "
#Listen {$port}
#NameVirtualHost {$ip}:{$port}

<VirtualHost {$ip}:{$port}>
    ServerName {$webgrindHostName}
    ServerAdmin webmaster@{$hostName}

    DocumentRoot {$documentRoot}
    <Directory />
        Options FollowSymLinks
        AllowOverride None
    </Directory>
    <Directory {$documentRoot}/>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride None
        Order allow,deny
        allow from all
    </Directory>

    ErrorLog {$log}/webgrind-error.log

    # Possible values include: debug, info, notice, warn, error, crit,
    # alert, emerg.
    LogLevel warn

    CustomLog {$log}/webgrind-access.log combined
</VirtualHost>
";

    // Add the vhost file.
    sudo("echo '' > {$vhostFile}");
    sudo("chmod 0777 {$vhostFile}");

    // Add the configuration.
    file_put_contents($vhostFile, trim($vhost));

    // Restrict rights.
    sudo("chown root:root {$vhostFile}");
    sudo("chmod 0644 {$vhostFile}");

    // Enable the Virtual host.
    sudo('a2ensite ' . pathinfo($vhostFile, PATHINFO_BASENAME));

    // Check if apache is running.
    if (strpos(
        strtolower(sudo('service apache2 status')),
        'not running'
    ) !== false
    ) {
        // Start apache.
        sudo('service apache2 restart');
    } else {
        // Reload apache.
        sudo('service apache2 force-reload');
    }

    echo "Installed the VirtualHost for {$webgrindHostName}\n";
} else {
    echo "VirtualHost already exists\n";
}
