#!/bin/bash

. include/bootstrap-root

OPWD=$(pwd)

# Prepare structure.
mkdir -p /www
cd /www

echo -e $SERVERPLOP"Installing webgrind"

# Detect the existence of the repo.
if grep -q 'Webgrind_MasterConfig' webgrind/index.php >/dev/null 2>&1; then
  # Update the repo.
  cd webgrind
  git pull >/dev/null 2>&1
else
  # Clone the repo.
  git clone https://github.com/jokkedk/webgrind >/dev/null 2>&1
fi

# Make it writeable.
chmod -R 0777 /www/webgrind

# Now enable the profile trigger.
if grep -q 'xdebug.profiler_enable_trigger' /etc/php5/apache2/php.ini >/dev/null 2>&1; then
  echo -e $SERVERPLOP"Agreed with current trigger value"
else
  echo -e $SERVERPLOP"Enabled profiling by trigger"
  echo "xdebug.profiler_enable_trigger = 1" >> /etc/php5/apache2/php.ini
fi

cd $OPWD

echo -e $SERVERPLOP"Make sure there is a VirtualHost pointing to /www/webgrind"
echo -e $SERVERPLOP"You can enable the grinding by adding the request parameter XDEBUG_PROFILE=1"
echo -e $SERVERPLOP"See https://code.google.com/p/webgrind/wiki/Installation for more information"
echo -e $SERVERPLOP"Finished webgrind"
