#!/bin/bash

# Exit the script when a command returns a non true value.
set -e
# Prevent using unset variables.
set -u

if [[ $EUID -ne 0 ]]; then
  echo "$0 must be run as root"
  exit 1
fi

BLUE="\033[0;34m";
PURPLE="\033[35m";
NOCLR="\033[0m";
SERVERPLOP=$PURPLE"[serverplop]"$NOCLR" ";
INFO=$BLUE"[serverplop]"$NOCLR" ";

echo -e $PURPLE"================================================================================"$NOCLR
echo -e "Running "$BLUE"$0"$NOCLR" as "$BLUE"$(whoami)"$NOCLR". . ."
echo -e $PURPLE"================================================================================"$NOCLR
