#!/bin/bash

# Exit the script when a command returns a non true value.
set -e
# Prevent using unset variables.
set -u

if [[ $EUID -ne 0 ]]; then
  echo "$0 must be run as root"
  exit 1
fi

OUTPUT="/etc/locale.gen"
DATE=$(date +%F)
BACKUP=$OUTPUT.$DATE

# Make a backup of the output file.
# cp -b will make a backup of the destination if it already exists.
cp -b $OUTPUT $BACKUP

LOCALES="\n
de_DE.UTF-8 UTF-8\n
en_GB.UTF-8 UTF-8\n
en_US.UTF-8 UTF-8\n
es_ES.UTF-8 UTF-8\n
fr_FR.UTF-8 UTF-8\n
it_IT.UTF-8 UTF-8\n
nl_NL.UTF-8 UTF-8\n
pl_PL.UTF-8 UTF-8\n
pt_PT.UTF-8 UTF-8\n
ru_RU.UTF-8 UTF-8\n
sv_SE.UTF-8 UTF-8\n
";

echo -e $LOCALES > $OUTPUT

locale-gen
