#!/bin/bash

# Exit the script when a command returns a non true value.
set -e
# Prevent using unset variables.
set -u

if [[ $EUID -ne 0 ]]; then
  echo "$0 must be run as root"
  exit 1
fi

apt-get autoremove -y
apt-get update -y
apt-get install -y \
  build-essential \
  curl \
  debhelper \
  denyhosts \
  gcc \
  git \
  htop \
  less \
  make \
  openssh-server \
  openssl \
  pari-gp \
  screen \
  sysstat \
  vim
