#!/bin/bash

. include/bootstrap-root

echo -e $SERVERPLOP"Installing dot"

if which dot >/dev/null 2>&1; then
  echo -e $SERVERPLOP"dot already installed"
  echo -e $SERVERPLOP"Running update"
  apt-get update -y >/dev/null 2>&1
else
  # Remove any existing symlink.
  rm -f /usr/local/bin/dot >/dev/null 2>&1

  apt-get update -y >/dev/null 2>&1
  apt-get install -y graphviz >/dev/null 2>&1

  # Create a symlink.
  # Especially helpful for third party software that tries to keep things
  # cross OS compatible, like webgrind.
  ln -s /usr/bin/dot /usr/local/bin/dot >/dev/null 2>&1
  chmod +x /usr/local/bin/dot >/dev/null 2>&1
fi

echo -e $SERVERPLOP"Finished installing dot"
