#!/bin/bash

# Exit the script when a command returns a non true value.
set -e
# Prevent using unset variables.
set -u

if [[ $EUID -ne 0 ]]; then
  echo "$0 must be run as root"
  exit 1
fi

apt-get update -y
apt-get install -y \
  cpanminus \
  libapache2-mod-perl2 \
  libapache2-mod-perl2-dev \
  libbusiness-creditcard-perl \
  libcgi-session-perl \
  libconfig-ini-perl \
  libconvert-pem-perl \
  libcrypt-openssl-rsa-perl \
  libcrypt-openssl-x509-perl \
  libcrypt-ssleay-perl \
  libdatetime-perl \
  libdbd-mysql-perl \
  liberror-perl \
  libfreezethaw-perl \
  libhtml-scrubber-perl \
  libhtml-strip-perl \
  libhtml-stripscripts-parser-perl \
  libhtml-stripscripts-perl \
  libhttp-browserdetect-perl \
  libjson-perl \
  libmail-rfc822-address-perl \
  libmime-lite-perl \
  libnet-sftp-foreign-perl \
  libnet-ssh-perl \
  libnet-ssleay-perl \
  libphp-serialization-perl \
  libreadonly-perl \
  libredis-perl \
  libsphinx-search-perl \
  libstring-approx-perl \
  libsys-syslog-perl \
  libtemplate-perl \
  libtemplate-perl-doc \
  libtemplate-plugin-xml-perl \
  libtext-unaccent-perl \
  libtime-modules-perl \
  libtime-piece-mysql-perl \
  liburi-encode-perl \
  libxml-simple-perl \
  libxml-xpath-perl \
  libyaml-libyaml-perl \
  libyaml-perl \
  libyaml-syck-perl

cpanm Geo::Distance
cpanm SOAP::Lite
cpanm URI::Escape::XS
cpanm Time::Piece
cpanm Digest::SHA1
