#!/bin/bash

. include/bootstrap-root

echo -e $SERVERPLOP"Installing PHPUnit"

apt-get update -y >/dev/null 2>&1
apt-get install -y php-pear >/dev/null 2>&1

pear config-set auto_discover 1 >/dev/null 2>&1
pear upgrade PEAR >/dev/null 2>&1
pear upgrade pear.phpunit.de/PHPUnit >/dev/null 2>&1
pear upgrade phpunit/DbUnit >/dev/null 2>&1
pear upgrade phpunit/PHP_Invoker >/dev/null 2>&1
pear upgrade phpunit/PHPUnit_Selenium >/dev/null 2>&1
pear upgrade phpunit/PHPUnit_Story >/dev/null 2>&1
pear upgrade phpunit/PHPUnit_SkeletonGenerator >/dev/null 2>&1
pear config-set auto_discover 0 >/dev/null 2>&1

echo -e $SERVERPLOP"Finished PHPUnit"
