#!/bin/bash

. include/bootstrap-root
. include/apt

# By default, Ubuntu 13.04 installs Smarty3.
# Let's check the version.
VERSION=$(dpkgversionorempty smarty | cut -d '.' -f 1 -s)

log "Installing Smarty 2"

if [[ "$VERSION" == "2" ]]; then
  loginfo "You currently already have Smarty v2 installed"
else
  aptremove smarty

  OPWD=$(pwd)
  URL="http://ubuntu.mirror.cambrium.nl/ubuntu/pool/universe/s/smarty/smarty_2.6.26-0.2ubuntu1_all.deb"

  cd /tmp

  run rm -f smarty2.6.deb

  log "Downloading package"
  run wget $URL -O smarty2.6.deb

  log "Installing package"
  run dpkg -i smarty2.6.deb
  run rm -f smarty2.6.deb

  cd $OPWD
fi

log "Finished Smarty 2"
alert update-manager "Finished Smarty 2"
loginfo "Please note that this is a security risk, not a feature"
