#!/bin/bash

if [[ $EUID -eq 0 ]]; then
  echo "$0 explicitly cannot be run as root!"
  exit 1
fi

OPAD=$(pwd)

cd /tmp

rm -rf square* && \
git clone https://github.com/observing/square.git && \
cd square && \
make update && \
make install && \
cd ../ && \
rm -rf square

cd $OPAD