#!/bin/bash

if [[ $EUID -eq 0 ]]; then
  echo "$0 explicitly cannot be run as root!"
  exit 1
fi

OPAD=$(pwd)

mkdir -p ~/tmp && \
chmod -R 0777 ~/tmp

mkdir -p ~/Applications/ && \
cd ~/Applications/

rm -rf square && \
git clone https://github.com/observing/square.git && \
cd square && \
make update && \
sudo make install && \

cd $OPAD