#!/bin/bash

if [[ $EUID -ne 0 ]]; then
  echo "$0 must be run as root"
  exit 1
fi

apt-get update -y && \
apt-get install denyhosts less vim make gcc git screen apache2 mysql-client php5 openssl smarty curl debhelper -y && \
apt-get install libapache2-mod-perl2-dev build-essential libxml-simple-perl liberror-perl libtemplate-perl libtemplate-perl-doc libreadonly-perl libtime-modules-perl libmime-lite-perl libapache2-mod-perl2 libtext-unaccent-perl libstring-approx-perl libhtml-scrubber-perl libcgi-session-perl libbusiness-creditcard-perl libnet-ssh-perl pari-gp php5-mysql -y && \
apt-get install libmail-rfc822-address-perl libconvert-pem-perl libcrypt-openssl-x509-perl libcrypt-ssleay-perl libcrypt-openssl-rsa-perl libdatetime-perl libnet-sftp-foreign-perl libnet-ssleay-perl libtemplate-plugin-xml-perl libphp-serialization-perl smarty libtime-piece-mysql-perl libjson-perl libhtml-strip-perl -y && \
apt-get install libhtml-stripscripts-parser-perl libhtml-stripscripts-perl libsys-syslog-perl libsphinx-search-perl libfreezethaw-perl libnet-sftp-foreign-perl libyaml-perl libyaml-libyaml-perl libyaml-syck-perl libhttp-browserdetect-perl php-htmlpurifier libredis-perl libconfig-ini-perl -y && \
apt-get install libxml-xpath-perl libdbd-mysql-perl liburi-encode-perl -y && \
apt-get install git openssh-server php5-curl -y && \
cpan Geo::Distance && \
cpan SOAP::Lite && \
cpan URI::Escape::XS && \
cpan Time::Piece && \
cpan Digest::SHA1

echo 'de_DE.UTF-8 UTF-8' >> /var/lib/locales/supported.d/local
echo 'en_GB.UTF-8 UTF-8' >> /var/lib/locales/supported.d/local
echo 'en_US.UTF-8 UTF-8' >> /var/lib/locales/supported.d/local
echo 'es_ES.UTF-8 UTF-8' >> /var/lib/locales/supported.d/local
echo 'fr_FR.UTF-8 UTF-8' >> /var/lib/locales/supported.d/local
echo 'it_IT.UTF-8 UTF-8' >> /var/lib/locales/supported.d/local
echo 'nl_NL.UTF-8 UTF-8' >> /var/lib/locales/supported.d/local
echo 'pl_PL.UTF-8 UTF-8' >> /var/lib/locales/supported.d/local
echo 'pt_PT.UTF-8 UTF-8' >> /var/lib/locales/supported.d/local
echo 'ru_RU.UTF-8 UTF-8' >> /var/lib/locales/supported.d/local
echo 'sv_SE.UTF-8 UTF-8' >> /var/lib/locales/supported.d/local

locale-gen