#!/bin/bash

# Exit the script when a command returns a non true value.
set -e
# Prevent using unset variables.
set -u

if [[ $EUID -ne 0 ]]; then
  echo "$0 must be run as root"
  exit 1
fi

apt-get update
apt-get install -y apache2
apt-get install -y build-essential
apt-get install -y curl
apt-get install -y debhelper
apt-get install -y denyhosts
apt-get install -y gcc
apt-get install -y git
apt-get install -y less
apt-get install -y libapache2-mod-perl2
apt-get install -y libapache2-mod-perl2-dev
apt-get install -y libbusiness-creditcard-perl
apt-get install -y libcgi-session-perl
apt-get install -y libconfig-ini-perl
apt-get install -y libconvert-pem-perl
apt-get install -y libcrypt-openssl-rsa-perl
apt-get install -y libcrypt-openssl-x509-perl
apt-get install -y libcrypt-ssleay-perl
apt-get install -y libdatetime-perl
apt-get install -y libdbd-mysql-perl
apt-get install -y liberror-perl
apt-get install -y libfreezethaw-perl
apt-get install -y libhtml-scrubber-perl
apt-get install -y libhtml-strip-perl
apt-get install -y libhtml-stripscripts-parser-perl
apt-get install -y libhtml-stripscripts-perl
apt-get install -y libhttp-browserdetect-perl
apt-get install -y libjson-perl
apt-get install -y libmail-rfc822-address-perl
apt-get install -y libmime-lite-perl
apt-get install -y libnet-sftp-foreign-perl
apt-get install -y libnet-sftp-foreign-perl
apt-get install -y libnet-ssh-perl
apt-get install -y libnet-ssleay-perl
apt-get install -y libphp-serialization-perl
apt-get install -y libreadonly-perl
apt-get install -y libredis-perl
apt-get install -y libsphinx-search-perl
apt-get install -y libstring-approx-perl
apt-get install -y libsys-syslog-perl
apt-get install -y libtemplate-perl
apt-get install -y libtemplate-perl-doc
apt-get install -y libtemplate-plugin-xml-perl
apt-get install -y libtext-unaccent-perl
apt-get install -y libtime-modules-perl
apt-get install -y libtime-piece-mysql-perl
apt-get install -y liburi-encode-perl
apt-get install -y libxml-simple-perl
apt-get install -y libxml-xpath-perl
apt-get install -y libyaml-libyaml-perl
apt-get install -y libyaml-perl
apt-get install -y libyaml-syck-perl
apt-get install -y make
apt-get install -y mysql-client
apt-get install -y openssh-server
apt-get install -y openssl
apt-get install -y pari-gp
apt-get install -y php-htmlpurifier
apt-get install -y php5
apt-get install -y php5-curl
apt-get install -y php5-mysql
apt-get install -y php5-xdebug
apt-get install -y screen
apt-get install -y smarty
apt-get install -y vim

cpan Geo::Distance
cpan SOAP::Lite
cpan URI::Escape::XS
cpan Time::Piece
cpan Digest::SHA1
