#!/bin/bash
. include/bootstrap-root
. include/apt

packages=('apache2');

# Install this module if Perl is available.
if which perl >/dev/null 2>&1; then
  packages=("${packages[@]}" 'libapache2-mod-perl2')
fi

# Install this module if PHP is available.
if which php >/dev/null 2>&1; then
  packages=("${packages[@]}" 'libapache2-mod-php5')
fi

log "Installing Apache2"

aptinstall ${packages[@]}

log "Finished Apache2"
