#!/bin/bash

. include/bootstrap

log "Installing Doxygen"

OPWD=$(pwd)

cd /tmp

# Remove trash.
sudo rm -rf doxygen-1.8.4* >/dev/null 2>&1

if which doxygen >/dev/null 2>&1; then
  log "Doxygen already installed. No update mechanism in place."
else

  dependencies=(
    'libqt4-gui'
    'qt4-dev-tools'
    'flex'
    'bison'
  );

  log "Installing dependencies"

  # Install dependencies for Doxywizard.
  sudo apt-get update -y >/dev/null 2>&1
  sudo apt-get install -y ${dependencies[@]} >/dev/null 2>&1

  log "Downloading archive"

  # Download the Doxygen package.
  wget http://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.4.src.tar.gz

  # Extract the package.
  gunzip doxygen-1.8.4.src.tar.gz
  tar xf doxygen-1.8.4.src.tar
  cd doxygen-1.8.4

  # Configure the package.
  sh ./configure --with-doxywizard

  log "Running installation"

  # Run the installation.
  make >/dev/null 2>&1
  sudo make install >/dev/null 2>&1

  cd /tmp

  # Remove trash.
  sudo rm -rf doxygen-1.8.4* >/dev/null 2>&1

  # Run the Doxywizard.
  doxywizard ~/Doxyfile >/dev/null 2>&1

  log "Your Doxyfile was stored in ~/Doxyfile"
fi

cd $OPWD

log "Finished Doxygen"
