#!/bin/bash

. include/bootstrap
. include/apt

log "Installing Doxygen"

dependencies=(
  'libqt4-gui'
  'qt4-dev-tools'
  'flex'
  'bison'
);

OPWD=$(pwd)
cd /tmp

# Remove trash.
sudo rm -rf doxygen-1.8.4* >/dev/null 2>&1

if which doxygen >/dev/null 2>&1; then
  log "Doxygen already installed."

  # Update dependencies for Doxywizard.
  aptinstall ${dependencies[@]}
else
  log "Installing dependencies"

  # Install dependencies for Doxywizard.
  aptinstall ${dependencies[@]}

  log "Downloading archive"

  # Download the Doxygen package.
  run wget http://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.4.src.tar.gz

  # Extract the package.
  run gunzip doxygen-1.8.4.src.tar.gz
  run tar xf doxygen-1.8.4.src.tar
  cd doxygen-1.8.4

  # Configure the package.
  run sh ./configure --with-doxywizard

  log "Running installation"

  # Run the installation.
  run make >/dev/null 2>&1
  run sudo make install >/dev/null 2>&1

  cd /tmp

  # Remove trash.
  sudo rm -rf doxygen-1.8.4* >/dev/null 2>&1

  # Run the Doxywizard.
  doxywizard ~/Doxyfile >/dev/null 2>&1

  log "Your Doxyfile was stored in ~/Doxyfile"
fi

cd $OPWD

loginfo "Installed version: doxygen $GREEN$(doxygen --version)$NOCLR"
log "Finished Doxygen"
