#!/bin/bash

. include/bootstrap-root
. include/apt

packages=(
  'build-essential'
  'curl'
  'debhelper'
  'denyhosts'
  'gcc'
  'git'
  'htop'
  'less'
  'make'
  'openssh-server'
  'openssl'
  'pari-gp'
  'sysstat'
  'vim'
);

log "Installing Linux essentials"

aptinstall ${packages[@]}

alert update-manager "Finished Linux Essentials for $DISTRIBUTOR $CODENAME"
log "Finished essentials"
