#!/bin/bash

. include/bootstrap-root

packages=(
  'build-essential'
  'curl'
  'debhelper'
  'denyhosts'
  'gcc'
  'git'
  'htop'
  'less'
  'make'
  'openssh-server'
  'openssl'
  'pari-gp'
  'screen'
  'sysstat'
  'vim'
);

echo -e $SERVERPLOP"Installing Linux essentials"
echo -e $SERVERPLOP"Selected packages: ${packages[@]}"

apt-get update -y >/dev/null 2>&1
apt-get install -y ${packages[@]} >/dev/null 2>&1

echo -e $SERVERPLOP"Finished essentials"
