#!/bin/bash

. include/bootstrap-root

log "Installing Graphviz"

if which dot >/dev/null 2>&1; then
  log "dot already installed"
  log "Running update"
  apt-get update -y >/dev/null 2>&1
else
  # Remove any existing symlink.
  rm -f /usr/local/bin/dot >/dev/null 2>&1

  apt-get update -y >/dev/null 2>&1
  apt-get install -y graphviz >/dev/null 2>&1

  # Create a symlink.
  # Especially helpful for third party software that tries to keep things
  # cross OS compatible, like webgrind.
  ln -s /usr/bin/dot /usr/local/bin/dot >/dev/null 2>&1
  chmod +x /usr/local/bin/dot >/dev/null 2>&1
fi

log "Finished Graphviz"
