#!/bin/bash

. include/bootstrap-root

SOURCE="/etc/apt/sources.list.d/webupd8team-java-raring.list"
FRESH=0

echo -e $SERVERPLOP"Installing Java 8"

# We have a version of Java installed. Not sure if it's OpenJDK or Sun.
if which java >/dev/null 2>&1; then
  # We found the source listing for the webupd8team. Assuming Sun's version is
  # installed.
  if ls $SOURCE >/dev/null 2>&1; then
    echo -e $SERVERPLOP"Skipping OpenJDK purge and source listing."
    FRESH=1
  fi
fi

# We found a fresh installation / an OpenJDK installation.
if [[ $FRESH -eq 0 ]]; then
  apt-get purge -y openjdk* >/dev/null 2>&1
  add-apt-repository ppa:webupd8team/java -y >/dev/null 2>&1
fi

# Update and install our Java.
apt-get update -y >/dev/null 2>&1
apt-get install oracle-java8-installer -y >/dev/null 2>&1

echo -e $SERVERPLOP"Finished Java 8"
