#!/bin/bash

. include/bootstrap-root

OUTPUT="/var/lib/locales/supported.d/local"
DATE=$(date +%F)
BACKUP=$OUTPUT.$DATE

LOCALES="\n
de_DE.UTF-8 UTF-8\n
en_GB.UTF-8 UTF-8\n
en_US.UTF-8 UTF-8\n
es_ES.UTF-8 UTF-8\n
fr_FR.UTF-8 UTF-8\n
it_IT.UTF-8 UTF-8\n
nl_NL.UTF-8 UTF-8\n
pl_PL.UTF-8 UTF-8\n
pt_PT.UTF-8 UTF-8\n
ru_RU.UTF-8 UTF-8\n
sv_SE.UTF-8 UTF-8\n
";

echo -e $SERVERPLOP"Installing locales"

if [[ "$(cat $OUTPUT)" == "$(echo -e $LOCALES)" ]]; then
  echo -e $SERVERPLOP"All locales are present and accounted for"
  echo -e $SERVERPLOP"Skipping locale-gen"
else
  # Make a backup of the output file.
  # cp -b will make a backup of the destination if it already exists.
  cp -b $OUTPUT $BACKUP >/dev/null 2>&1

  echo -e $LOCALES > $OUTPUT 2>&1
  echo -e $SERVERPLOP"Generating locales"
  locale-gen >/dev/null 2>&1
fi

echo -e $SERVERPLOP"Finished locales"
