#!/bin/bash

. include/bootstrap-root
. include/apt

packages=(
  'mysql-server'
  'mysql-client'
);

# Install the php5-mysql package if php is available.
if which php >/dev/null 2>&1; then
  packages=("${packages[@]}" 'php5-mysql')
fi

# Install this if Perl is available.
if which perl >/dev/null 2>&1; then
  packages=("${packages[@]}" 'libdbd-mysql-perl' 'libtime-piece-mysql-perl')
fi

log "Installing MySQL"

aptinstall ${packages[@]}

log "Finished MySQL"
