#!/bin/bash

. include/bootstrap-root
. include/apt
. include/cpanm

packages=(
  'cpanminus'
  'libbusiness-creditcard-perl'
  'libcgi-session-perl'
  'libconfig-ini-perl'
  'libconvert-pem-perl'
  'libcrypt-openssl-rsa-perl'
  'libcrypt-openssl-x509-perl'
  'libcrypt-ssleay-perl'
  'libdatetime-perl'
  'liberror-perl'
  'libfreezethaw-perl'
  'libhtml-scrubber-perl'
  'libhtml-strip-perl'
  'libhtml-stripscripts-parser-perl'
  'libhtml-stripscripts-perl'
  'libhttp-browserdetect-perl'
  'libjson-perl'
  'libmail-rfc822-address-perl'
  'libmime-lite-perl'
  'libnet-sftp-foreign-perl'
  'libnet-ssh-perl'
  'libnet-ssleay-perl'
  'libreadonly-perl'
  'libredis-perl'
  'libsphinx-search-perl'
  'libstring-approx-perl'
  'libsys-syslog-perl'
  'libtemplate-perl'
  'libtemplate-perl-doc'
  'libtemplate-plugin-xml-perl'
  'libtext-unaccent-perl'
  'libtime-modules-perl'
  'libtime-piece-mysql-perl'
  'liburi-encode-perl'
  'libxml-simple-perl'
  'libxml-xpath-perl'
  'libyaml-libyaml-perl'
  'libyaml-perl'
  'libyaml-syck-perl'
);

# Install this module if Apache2 is available.
if ls /etc/init.d/apache2 >/dev/null 2>&1; then
  packages=("${packages[@]}" 'libapache2-mod-perl2' 'libapache2-mod-perl2-dev')
fi

# Install these modules if MySQL is available.
if ls /etc/init.d/mysql >/dev/null 2>&1; then
  packages=("${packages[@]}" 'libdbd-mysql-perl' 'libtime-piece-mysql-perl')
fi

# Install this if PHP is available.
if which php >/dev/null 2>&1; then
  packages=("${packages[@]}" 'libphp-serialization-perl')
fi

log "Installing perl"

aptinstall ${packages[@]}

# CPAN distributions.
distributions=(
  'Geo::Distance'
  'SOAP::Lite'
  'URI::Escape::XS'
  'Time::Piece'
  'Digest::SHA1'
);

cpanminstall ${distributions[@]}

alert update-manager "Finished Perl" $(perl -e 'print $^V')
log "Finished perl"
