#!/bin/bash

. include/bootstrap-root

packages=(
  'php-htmlpurifier'
  'php5'
  'php5-cli'
  'php5-common'
  'php5-curl'
  'php5-gd'
  'php5-imagick'
  'php5-mcrypt'
);

# Install this module if Apache2 is available.
if ls /etc/init.d/apache2 >/dev/null 2>&1; then
  packages=("${packages[@]}" 'libapache2-mod-php5')
fi

# Install the mysql package if the server is available.
if ls /etc/init.d/mysql >/dev/null 2>&1; then
  packages=("${packages[@]}" 'php5-mysql')
fi

# Install this if Perl is available.
if which perl >/dev/null 2>&1; then
  packages=("${packages[@]}" 'libphp-serialization-perl')
fi

echo -e $SERVERPLOP"Installing PHP"
echo -e $SERVERPLOP"Selected packages: ${packages[@]}"

apt-get update -y >/dev/null 2>&1
apt-get install -y ${packages[@]} >/dev/null 2>&1

echo -e $SERVERPLOP"Finished PHP"
