#!/bin/bash

. include/bootstrap

keyfile="/home/$USER/.ssh/id_rsa.pub"

log "Running public SSH key tool"

# We want to check if we have a public SSH key.
# If not, we should create one.
if ls $keyfile >/dev/null 2>&1; then
  log "Found a public key file at $keyfile"
else
  echo -e $INFO"Enter your e-mail address (i.e. the one you use for github): "
  read email
  ssh-keygen -t rsa -C "$email" -f $keyfile
  log "You can find your key in $keyfile"
fi

log "Finished public SSH key tool"
