#!/bin/bash

. include/bootstrap

OPAD=$(pwd)

echo -e $SERVERPLOP"Installing [square]"

mkdir -p ~/tmp >/dev/null 2>&1
sudo rm -rf ~/tmp/node* >/dev/null 2>&1
chmod -R 0777 ~/tmp >/dev/null 2>&1

mkdir -p ~/Applications/ >/dev/null 2>&1
cd ~/Applications/

NEEDCLONE=0

if ls square >/dev/null 2>&1; then
  echo -e $SERVERPLOP"Using existing square repo"
  cd square

  if git pull >/dev/null 2>&1; then
    echo -e $SERVERPLOP"Using updated source files via git pull"
    NEEDCLONE=1
  fi

  cd ..
fi

if [[ $NEEDCLONE -eq 0 ]]; then
  rm -rf square >/dev/null 2>&1
  echo -e $SERVERPLOP"Cloning the repo"
  git clone https://github.com/observing/square.git >/dev/null 2>&1
fi

cd square

echo -e $SERVERPLOP"Running installation"

make update >/dev/null 2>&1
sudo make install >/dev/null 2>&1

cd $OPAD

echo -e $SERVERPLOP"Finished [square]"
