#!/bin/bash

. include/bootstrap

OPAD=$(pwd)

log "Installing [square]"

mkdir -p ~/tmp >/dev/null 2>&1
sudo rm -rf ~/tmp/node* >/dev/null 2>&1
chmod -R 0777 ~/tmp >/dev/null 2>&1

mkdir -p ~/Applications/ >/dev/null 2>&1
cd ~/Applications/

NEEDCLONE=0

if ls square >/dev/null 2>&1; then
  log "Using existing square clone"
  cd square

  if git pull >/dev/null 2>&1; then
    log "Using updated source files via git pull"
    NEEDCLONE=1
  fi

  cd ..
fi

if [[ $NEEDCLONE -eq 0 ]]; then
  rm -rf square >/dev/null 2>&1
  log "Cloning the repo"
  git clone https://github.com/observing/square.git >/dev/null 2>&1
fi

cd square

log "Running installation"

make update >/dev/null 2>&1
sudo make install >/dev/null 2>&1

cd $OPAD

log "Finished [square]"
