#!/bin/bash
. include/bootstrap
. include/apt

log "Installing developer tools"

# A tool for maintaining multiple SSH terminals through a single command input.
log "Installing Cluster SSH"
aptinstall clusterssh
log "Finished Cluster SSH"

# A tool for jumping to directories based on visit behavior.
log "Installing Z"

OPWD=$(pwd)
mkdir -p ~/Applications/ >/dev/null 2>&1
cd ~/Applications

if [ -d z ]; then
  log "Using existing z clone. Updating."
  cd z
  run git pull
else
  log "Cloning into z"
  run git clone git://github.com/rupa/z.git
fi

if [ -f ~/.bashz ]; then
  log "Found existing source file. Skipping symlink."
else
  log "Creating symlink."
  cd ~
  ln -s ~/Applications/z/z.sh .bashz
fi

if grep ". ~/.bashz" ~/.bashrc >/dev/null 2>&1; then
  log "Found source inclusion. Skipping installation."
else
  log "Installing Z"
  echo ". ~/.bashz" >> ~/.bashrc 2>&1

  loginfo "Z is a directory jumping tool, which jumps based on directory visit history."
  loginfo "'z plop' would most likely bring you to the serverplop repo."
  loginfo "Note that your currently active shell won't have z enabled yet."
  loginfo "Please restart your shell/terminal for z to take effect."
fi

log "Finished Z"

log "Finished developer tools"
