#!/bin/bash

function dpkgversion {
  dpkg -s $1 | grep 'Version:' | head -n 1 | awk -F ': ' '{ print $NF }'
}

function dpkglist {
  loginfo "Installed packages:"

  for package in $@; do
    if dpkgversion $package >/dev/null 2>&1; then
      loginfo "- $package $GREEN$(dpkgversion $package)$NOCLR"
    else
      logerror "- $package not installed!"
    fi;
  done
}

function aptinstall {
  log "Selected packages: $@"

  sudo apt-get update -y >/dev/null 2>&1
  sudo apt-get install -y $@ >/dev/null 2>&1

  dpkglist $@
}
