#!/bin/bash

function dpkgversion {
  dpkg -s $1 | grep 'Version:' | head -n 1 | awk -F ': ' '{ print $NF }'
}

function dpkgversionorempty {
  if dpkgversion $1 >/dev/null 2>&1; then
    dpkgversion $1
  else
    echo ""
  fi
}

function dpkglist {
  loginfo "Installed packages:"

  for package in $@; do
    if dpkgversion $package >/dev/null 2>&1; then
      loginfo "- $package $GREEN$(dpkgversion $package)$NOCLR"
    else
      logerror "$package not installed!"
      exit 1
    fi;
  done
}

function aptinstall {
  log "Selected packages: $@"

  run sudo apt-get update -y
  run sudo apt-get install -y $@

  dpkglist $@
}

function aptremove {
  log "Removing packages: $@"

  run sudo apt-get purge -y $@
  run sudo apt-get update -y

  log "Removed packaged: $@"
}
