#!/bin/bash

# Exit the script when a command returns a non true value.
set -e
# Prevent using unset variables.
set -u

echo ""

if [[ $EUID -ne 0 ]]; then
  echo "$0 must be run as root"
  exit 1
fi

. include/settings

echo -e $NOCLR$LINE
echo -e "Running "$BLUE"$0"$NOCLR" as "$ROOTCLR"$(whoami)"$NOCLR". . ."
echo -e $LINE
