#!/bin/bash

function log {
  echo -e $SERVERPLOP"$@"
}

function loginfo {
  echo -e $INFO"$@"
}

# Currently dead code. Had need for this when trying to add a new installation.
# I gave up on that installation, but the function is probably still useful.
function findlib {
  if ls $DISTRIBUTOR"/"$CODENAME"/lib/"$1 >/dev/null 2>&1; then
    ls $DISTRIBUTOR"/"$CODENAME"/lib/"$1
  else
    if ls $DISTRIBUTOR"/lib/"$1 >/dev/null 2>&1; then
      ls $DISTRIBUTOR"/lib/"$1
    else
      ls "lib/"$1
    fi
  fi
}
