#!/bin/bash

function log {
  echo -e $SERVERPLOP"$@"
}

function loginfo {
  echo -e $INFO"$@"
}

function logerror {
  echo -e $ERROR"$@"
}

function spinner {
  while [ -d /proc/$1 ]; do
    echo -en $GREEN'/\x08';
    sleep .1

    echo -en $GREEN'-\x08';
    sleep .1

    echo -en $GREEN'\x08';
    sleep .1

    echo -en $GREEN'|\x08';
    sleep .1

    tput sgr0;
  done;

  echo -en $NOCLR;
}

function run {
  # If the command is prefixed with sudo, we want to echo something as sudo.
  # Otherwise, the spinner will mess with the password input.
  if [[ $(echo "$@" | cut -d ' ' -f 1) -eq "sudo" ]]; then
    sudo echo -en ''
  fi

  # Run the process in the background and tie it to a spinner.
  $@ >/dev/null 2>&1 &
  spinner $!
}

# Currently dead code. Had need for this when trying to add a new installation.
# I gave up on that installation, but the function is probably still useful.
function findlib {
  if ls $DISTRIBUTOR"/"$CODENAME"/lib/"$1 >/dev/null 2>&1; then
    ls $DISTRIBUTOR"/"$CODENAME"/lib/"$1
  else
    if ls $DISTRIBUTOR"/lib/"$1 >/dev/null 2>&1; then
      ls $DISTRIBUTOR"/lib/"$1
    else
      ls "lib/"$1
    fi
  fi
}
