#!/bin/bash

function pearversion {
  # Get info about our package.
  pear info $1 | \
  # Grep the version.
  grep 'Release Version' | \
  # Remove the first part of the string.
  awk -F '  ' '{print $NF }'
}

function pearlist {
  loginfo "Installed PEAR packages:"

  for package in $@; do
    if pearversion $package >/dev/null 2>&1; then
      loginfo "- $package$GREEN$(pearversion $package)$NOCLR"
    else
      logerror "- $package not installed!"
    fi;
  done
}

function pearinstall {
  log "Installing dependency: php-pear"

  run sudo apt-get update -y
  run sudo apt-get install -y php-pear

  log "Enabled auto_discover"
  run sudo pear config-set auto_discover 1

  log "Selected packages: $@"
  run pear upgrade PEAR $@

  log "Disabled auto_discover"
  sudo pear config-set auto_discover 0 >/dev/null 2>&1

  pearlist $@
}
